- .golangci.yml
- pkg/client/actionclient_test.go
- Enable lint goconst
- Fix its issue
blocked by: #5
> .golangci.yml: Enable goconst and fix issues

- example/Makefile
Applied the kustomize impl from kb
> Makefile: install kustomize if not installed

- .github/workflows/ci.yml
Move lint task to separate job
> .github/workflows: move linting to separate job

- Dockerfile
- Makefile
- example/Makefile
- example/config/samples/helm_v1_nginx.yaml
- go.mod
- internal/cmd/run/cmd.go
- internal/cmd/version/cmd.go
- internal/version/version.go
- pkg/annotation/annotation.go
- pkg/client/client_suite_test.go
- pkg/internal/testutil/testutil.go
- pkg/manager/manager_suite_test.go
- pkg/reconciler/reconciler_suite_test.go
updates based on SDK's helm-operator 1.0.0
> updates based on SDK's helm-operator 1.0.0

- go.sum
- main.go
Add support for kubebuilder init and create API scaffolding
> added scaffolding to project

- .github/workflows/ci.yml
- .gitignore
- .golangci.yml
- Makefile
- tools/scripts/fetch
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
> *: Makefile and other general improvements

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .goreleaser.yml
Sign release binaries during GoReleaser deploy phase.
> Add support for signing releases with GoReleaser

- pkg/annotation/annotation.go
Added documentation for the annotation package. 
Fixes #90
> Add annotation package docs

- pkg/plugins/hybrid/v1alpha/scaffolds/init.go
Update scaffolding version of plugins to upcode release.
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
> [release PR] Release prep PR 0.0.8

- pkg/plugins/hybrid/v1alpha/scaffolds/init.go
- pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/gomod.go
update scaffolding for 0.0.9 release
> update scaffolding for 0.0.9 release

- tools/scripts/fetch
fix the goreleaser fetch script
resolves #171
> fix goreleaser fetch script

- pkg/plugins/hybrid/v1alpha/scaffolds/init.go
Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
> release v0.0.11 prep

- go.mod
- go.sum
Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
> update kubebuilder to latest commit

- pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/dockerfile.go
- testdata/hybrid/memcached-operator/Dockerfile
> OCPBUGS-11569: Switch to ubi-micro:8.7

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
Pin to v5
Update config to v5 syntax
Fixes #252
> Fix PR labeler workflow

- pkg/manager/namespace_test.go
> Restore accidentally deleted test code

- go.mod
- go.sum
- pkg/watches/watches.go
> bump github.com/go-task/slim-sprig to v3.0.0

- .github/workflows/ci.yml
- this is a backport from `main`
> update ci to run on all pull requests, no matter the branch

- testdata/hybrid/memcached-operator/go.mod
- testdata/hybrid/memcached-operator/go.sum
> fix test data scaffolding code

- pkg/client/actionclient.go
- pkg/client/actionclient_test.go
- pkg/reconciler/internal/fake/actionclient.go
In order to give users of this library more information about the state of a release, we are adding the `History` method to the `ActionClient` interface. 
Without this, the only information available via the `ActionClient` about a release is the latest revision (via the `Get` method). However this proves insufficient if callers need to know details of release history, for example if an upgrade failed and callers want to know about the most recently deployed release.
> pkg/client: add history method to ActionClient

- pkg/internal/predicate/predicates.go
> pkg/internal/predicate: remove status subresource managed field
