operator-framework/helm-operator-plugins

Makefile
The controller-gen is not required at all. See that it is used in kb just to gen te tesdata. 
Also, we have no markers in the code impl.
=> Makefile: remove unnecessary controller-gen & generate targets

.github/workflows/ci.yml
Fixes #64
Ref: https://github.com/golangci/golangci-lint-action#how-to-use
=> Update lint-action to v2

Makefile, pkg/plugins/v1/scaffolds/internal/templates/makefile.go
Folks may have docker aliased to Podman, and it prefers options before positional arguments.
=> Added default Dockerfile path to end of command

pkg/client/actionclient.go, pkg/client/actionclient_test.go
This PR build's on #70 (I will rebase when that merges).
Credit to @mikeshng for this (see https://github.com/operator-framework/operator-sdk/pull/4389)
**Description of the change:**
Helm operator: updated the ownerRefInjectingClient to not inject the owner references if it contains the annotation: 
```
annotations:
"helm.sh/resource-policy": keep
```
see https://helm.sh/docs/howto/charts_tips_and_tricks/ for more details about the `keep` annotation.
**Motivation for the change:**
For the Helm operator delete CR, namespace scope resources with the Helm keep annotation are being GC'ed by Kubernetes.
This change is to make sure those resources are not owned by the CR so they won't get GC'ed.
Closes: https://github.com/operator-framework/operator-sdk/issues/4378
After this change, I can no …
=> fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation

Dockerfile
Fix github deploy stage by bumping helm-operator Dockerfile to golang:1.15
=> Use golang:1.15 in helm-operator Dockerfile

go.mod, internal/cmd/run/cmd.go, internal/metrics/metrics.go
SDK update from:  Build info metric: [operator-framework/operator-sdk#4220](https://github.com/operator-framework/operator-sdk/pull/4220)
=> add build info metric

.github/workflows/ci.yml, Dockerfile, Makefile
The improvements are:
- Upgrade to docker/build-push-action@v2
- For PR events, run docker builds without pushing
- Use docker buildx to build multi-arch images (amd64, arm64, ppc64le, s390x)
=> Improve deploy stage in Github Actions CI workflow

.github/workflows/ci.yml, .github/workflows/deploy.yml, .gitignore, .goreleaser.yml, Makefile
This PR adds a goreleaser make target and updates the github actions
workflows to run the deploy stages (GoReleaser and Docker) for tags
and PRs (PR artifacts aren't pushed anywhere).
=> Add "release" makefile target and github action to run GoReleaser 

Makefile, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
If the current release is in the Failed or Superseded state, force an upgrade. This resolves a potential issue where a failed or superceded release is never redeployed.
See https://github.com/joelanford/helm-operator/issues/63#issuecomment-766509014
=> pkg/reconciler: force upgrade if release is failed or superseded

pkg/client/actionclient.go, pkg/client/actionclient_test.go, pkg/manifestutil/manifest_suite_test.go, pkg/manifestutil/resourcepolicykeep.go, pkg/manifestutil/resourcepolicykeep_test.go, pkg/reconciler/internal/hook/hook.go, pkg/reconciler/internal/hook/hook_test.go
This PR fixes a bug where resources with the `helm.sh/resource-policy: keep` annotation were not correctly watched in certain cases.
Closes #82
=> objects with resource policy "keep" should use the annotation-based watch

pkg/plugins/hybrid/v1alpha/init.go, pkg/plugins/hybrid/v1alpha/scaffolds/init.go, pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/dockerfile.go, pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/main.go
This commit:
1. Adds additional customizations to be done in config/ as
post-scaffolding step in init command.
2. Modify Dockerfile template.
3. Modify main.go to accept additional flags for watches.yaml and
leader-election-id.
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
TODO:
=> Update hybrid plugin scaffolding

Makefile
BSD sed (as shipped with MacOS) does not support `+` nor `\+` in regular expressions.
However it does support `\{1,\}` which does the same thing and is also supported by GNU sed.
Moreover, bash 3.2 (as shipped with MacOS) does not seem to support `source <(...)`, it seems to just do nothing.
Using plain eval seems to do the trick though.
Symptom of the former issue is:
```
source <(setup-envtest use -p env v0.22.1) && go test -race -covermode atomic -coverprofile cover.out ./...
version be a valid version, or simply 'latest' or 'latest-on-disk': unable to parse "v0.22.1" as a version stringshould be X.Y.Z, where Z may be '*','x', or left off entirely to denote a wildcard, optionally prefixed by ~|<|<=, and optionallyfollowed by ! (latest remote version)
```
And of the latter:
```
unable …
```
=> Support BSD sed and older bash in test rule.

pkg/reconciler/internal/hook/hook.go, pkg/reconciler/internal/hook/hook_test.go
This commit modifies `dependentResourceWatcher` to
accept `List` kinds while watching dependent resources.
It also adds test to verify if `setWatchOnResource`
works for lists.
Reference: https://github.com/operator-framework/operator-sdk/pull/4682
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
Closes: #89
=> Add option to watch List object types

pkg/client/actionclient.go, pkg/client/actionclient_test.go
The change filters out empty patches generated from the 3-way merge,
which could be in the form of the "{}" byte array that
represents an empty map.
Reference: https://github.com/operator-framework/operator-sdk/pull/4957
Co-authored-by: Cheuk Lam
=> fix(helm-operator): do not send empty patch requests to kube apiserver

README.md
This PR adds a basic quick start and introduction documentation for the hybrid Helm operator.
=> Add Quick Start and Introduction documentation

pkg/reconciler/internal/values/values.go, pkg/reconciler/internal/values/values_test.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go, pkg/values/values.go
A Translator is a way to produces helm values based on the fetched custom
resource itself (unlike `Mapper` which can only see `Values`).
This way the code which converts the custom resource to Helm values can first
convert an `Unstructured` into a regular struct, and then rely on Go type
safety rather than work with a tree of maps from `string` to `interface{}`.
Thanks to having access to a `Context`, the code can also safely access the
network, for example in order to retrieve other resources from the k8s cluster,
when they are referenced by the custom resource.
Fixes: #113
=> Add a WithValueTranslator option to Reconciller.

docs/Welcome.md, docs/project_layout.md, docs/tutorial.md
This PR creates a tutorial, quick overview and project
layout related doc for hybrid helm operator.
=> Add tutorial on hybrid helm based operators

.github/workflows/ci.yml, internal/cmd/helm-operator/run/cmd.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
This PR:
- returns the possible error earlier (in `reconciler.New` rather than during `SetupWithManager`).
- simplifies the logic in `setupWatches`
- adds tests for the `WithSelector` option setup.
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
=> refactor: parse selector in WithSelector option

pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_suite_test.go, pkg/reconciler/reconciler_test.go
Add a new Reconciler option `SkipGenericGVKSchemeRegistration `, which can be used by users who prefer their
custom scheme setup over the generic scheme setup currently being done by the reconciler.
Signed-off-by: Moritz Clasmeier <moritz@stackrox.com>
=> New Reconciler Option: SkipPrimaryGVKSchemeRegistration

pkg/reconciler/reconciler.go
Added two debugging log messages in reconciler
Signed-off-by: Moritz Clasmeier <moritz@stackrox.com>
=> Added two debugging log messages in reconciler

.github/workflows/ci.yml, .github/workflows/deploy.yml, .goreleaser.yml, Dockerfile, Makefile
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
=> consistently use go 1.17 throughout repository

pkg/client/actionclient.go
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
=> Check uninstall error is not nil when uninstalling a failed install

internal/cmd/helm-operator/run/cmd.go, internal/cmd/hybrid-operator/run/cmd.go
Add logging of the manager options for both the helm and hybrid operator commands
resolves #24
=> log manager options

pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/dockerfile.go, testdata/hybrid/memcached-operator/Dockerfile
We bumped Go version to 1.18 but missed the Dockerfile. This PR updates the Dockerfile to use Go 1.18.
=> bump go to 1.18 in scaffolded Dockerfile

pkg/client/restclientgetter.go
=> Make a copy of rest.Config provided to k8s.io/cli-runtime.

docs/tutorial.md, pkg/plugins/hybrid/v1alpha/scaffolds/init.go, pkg/plugins/util/cleanup.go, testdata/hybrid/memcached-operator/config/default/kustomization.yaml
=> updated v1alpha scaffolding

pkg/plugins/helm/v1/api.go, pkg/plugins/util/message.go
This will fix #185 
I added a warning message for the deprecated flag. PLease take a look once.
=> added warning message for deprecated flag

go.mod, pkg/client/actionclient_test.go, pkg/client/actionconfig.go, pkg/client/actionconfig_test.go, pkg/client/restclientgetter.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
When investigating high memory usage in the RHACS operator, profiling showed that most of the memory consumed by the discovery client's processing of the OpenAPI schema:
The profile seemed odd because an ever-growing amount of memory is allocated in a `sync.Once`, suggesting repeated execution.
After a debugging run, I found that the `ActionClientGetter` essentially creates:
- a `restClientGetter`, with a per-instance lazily created, cached discovery client (seems minor)
- one `k8s.io/kubectl/pkg/cmd/util.Factory` instance via the `kube.New(rcg)` call
- another `Factory` via the `cmdutil.NewFactory(rcg)` call (only used for the secrets clients)
- a `kubernetes.ClientSet` (seems minor)
for **each** reconciliation of **each** CR managed by the operator. The major impact is that each factory …
=> Fix memory leak due to misuse of K8s clients

Makefile
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
=> Removing duplicate fix target

pkg/internal/status/conditions.go, pkg/internal/status/conditions_test.go
The code as well as the test only require a `PassiveClock`, i.e., a clock that only supports querying the current time, without the ability to schedule future tasks in the style of `time.After`. That allows the use of a `SimpleIntervalClock`, which is not deprecated.
Note: `IntervalClock` doesn't do anything more than `SimpleIntervalClock`, as all the methods not implemented by `SimpleIntervalClock` would just panic anyway.
=> Use the non-deprecated SimpleIntervalClock fake kubeclock

pkg/client/actionclient.go, pkg/client/actionclient_test.go, pkg/client/actionconfig.go, pkg/client/actionconfig_test.go, pkg/reconciler/reconciler.go
This PR adds
In `ActionConfigGetter` constructor:
- Use a custom mapper in the action config getter to map an object to the helm client's configured namespace
- Use a custom mapper in the action config getter to map an object to the namespace where the release secret is stored
- Configure whether or not the release secret will have an owner reference to the object for which the `action.Configuration` is generated.
These are useful to give users of this library more control to decouple release storage from install namespace.
In `ActionClientGetter` constructur:
- Append custom default functional options used to create `action.Get`, `action.Install`, `action.Upgrade`, `action.Uninstall`, and `action.Rollback`.
These are useful to give users of this library the ability to customize how the …
=> Add various functional options to ActionConfigGetter and ActionClientGetter constructors

pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/makefile.go, testdata/hybrid/memcached-operator/Makefile
This is to update the makefile template so that when a hybrid helm operator is skaffolded the hybrid controller is used instead of the pre-built one supplied with operator sdk
=> Use hybrid controller instead of the pre-built version

docs/tutorial.md
"project layout" link is broken. So, fix it.
=> Fix broken link in tutorial

.goreleaser.yml, Makefile, pkg/plugins/hybrid/v1alpha/scaffolds/internal/templates/dockerfile.go, testdata/hybrid/memcached-operator/Dockerfile
**Description**:
- Removes all `CGO_ENABLED=0` references
**Motivation**:
- We shouldn't block builds from being able to be FIPS compliant by hardcoding the CGO_ENABLED=0 setting throughout our code
=> (dx): remove explicit CGO_ENABLED=0 to not block FIPS compliant builds/confusion

pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
Expose generic mechanism for configuring the controller, allowing to add additional watch sources.
Signed-off-by: Moritz Clasmeier <moritz@stackrox.com>
=> Expose generic mechanism for configuring the controller builder

pkg/reconciler/reconciler_test.go
Merging #153 broke main since it was using an plder version of controller-runtime. This commit fixes the same.
=> fix: fix a broken method on `main` branch

go.mod, pkg/reconciler/internal/updater/updater.go, pkg/reconciler/internal/updater/updater_test.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
The current logic will apply the finalizer to the custom resource after the first reconciliation loop (in a closure). Though, in certain circumstances, the custom resource might get deleted after the first reconciliation loop has installed the chart but before it has applied the finalizer. If the chart created any resources not in the same namespace these will be orphaned without cleanup.
By ensuring that the finalizer is present on the custom resource before proceeding, this will ensure a proper cleanup in all cases.
=> Ensure finalizer is present before reconciling

.github/workflows/ci.yml, .github/workflows/deploy.yml
In the deploy workflow, using a push branch config of ** results in it trying to gpg init for branches created by dependabot or anyone/anything else. This is not what we want - we want those covered by pull request events.
Change the config to only handle pushes to main (and continue to handle all tags and all PRs).
Also adjust the ci workflow similarly.
=> workflows: don't process all branches

go.mod, pkg/client/actionclient.go, pkg/client/actionclient_test.go, pkg/client/actionconfig.go, pkg/client/actionconfig_test.go, pkg/client/postrenderer_test.go, pkg/client/restclientgetter.go, pkg/client/restclientgetter_test.go, pkg/reconciler/internal/fake/actionclient.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go, testdata/hybrid/memcached-operator/go.mod
=> actionConfigGetter: allow custom mapping from object to rest.Config

.github/workflows/ci.yml
* `functionalities` param is no longer exist. It was used to enable file fixes to ignore common lines from coverage. This feature is now seems to be on by default.
* Adding `disable_search` because we do not need for the codecov action to search for coverage files: we explicitly provide files.
=> Fix codecov-action params

pkg/client/postrenderer_test.go, pkg/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go, pkg/reconciler/reconciler.go
=> reconciler: use server-side dry-run to generate candidate upgrade manifest

pkg/client/actionclient.go, pkg/client/actionclient_test.go
When an install fails, we uninstall the failed release. When an upgrade fails, we rollback to the previous release.
This commit makes it possible to disable that behavior, which results in the latest release being left in a Failed state for the caller to decide how to act.
=> ActionClientGetter: allow disabling rollbacks after failures

pkg/client/actionconfig.go, pkg/client/actionconfig_test.go, pkg/client/ownerrefclient.go, pkg/storage/chunked.go, pkg/storage/chunked_test.go, pkg/storage/labels.go, pkg/storage/storage_suite_test.go
This commit adds a custom helm release storage driver that overcomes limitations in the size of a single value that can be stored in etcd.
In order to remain backward-compatible and also make this storage driver available, this commit also refactors the ActionConfigGetter options so that a custom function can be provided to the ActionConfigGetter that can create the desired storage driver.
This commit also separates the rest config mapping into two separate options. One for interactions with the storage backend, and the other for managing release content.
=> ✨ Add support for a chunked release storage driver

pkg/plugins/hybrid/v1alpha/scaffolds/init.go
- release prep pr
- pr after this is released to fix the scafolding since that does a `go get` and errors.
```
ERRO[0003] error creating the project: /helm-operator-plugins/bin/helm-operator-plugins init --plugins hybrid/v1-alpha --repo github.com/example/memcached-operator failed with error: (exit status 1) time="2024-07-17T21:59:54Z" level=info msg="Writing kustomize manifests for you to edit..."
Writing scaffolds for you to edit...
time="2024-07-17T21:59:54Z" level=info msg="Get helm-operator-plugins:\n$ go get github.com/operator-framework/helm-operator-plugins@v0.2.2"
go: github.com/operator-framework/helm-operator-plugins@v0.2.2: invalid version: unknown revision v0.2.2
Error: failed to initialize project: unable to scaffold with "hybrid.helm.sdk.operatorframework.io/v1-alpha": exit …
```
=> update version in prep for v0.2.2

pkg/reconciler/internal/updater/updater.go, pkg/reconciler/internal/updater/updater_test.go, pkg/reconciler/internal/values/values.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
=> reconciler: fix deletion wait and updater retry logic

pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
```
defer func() {
applyErr := u.Apply(ctx, obj)
// Problem: err is not assigned to return value  
if err == nil && !apierrors.IsNotFound(applyErr) {
err = applyErr
}
}()
```
=> fix: error being silenced during apply

pkg/storage/chunked.go, pkg/storage/chunked_test.go, pkg/storage/labels.go
Release labels are currently stored only in Kubernetes object metadata, which limits what can actually be stored there.
In order to support a wider variety of release labels, we will only store system labels in the index secret. All custom release labels will be serialized in the release blob itself.
=> pkg/storage: handle more possible release label k/v pairs

go.mod
Downstream users may not be using latest z-streams of go, so this brings it down to the lowest z-stream allowable by the code.
=> Bring go.mod to lowest 1.22 z-stream compatible with the code

pkg/client/actionclient.go, pkg/client/actionclient_test.go, pkg/reconciler/internal/fake/actionclient.go
This PR exposes `action.Configuration` of a specific `actionClient` instance via new `Config` method. 
General motivation behind it is for the users to have an 'escape hatch' access to the underlying dependency objects that `action.Configuration` holds, which include for example:
- release records store
- registry client
- Kubernetes API client
More specific motivation comes from a scenario where an access to the underlying release store instance is needed in order to gracefully handle pending helm releases which were previously interrupted.
For additional context on this, see:
https://github.com/operator-framework/operator-controller/pull/1776
and more specifically this thread: https://github.com/operator-framework/operator-controller/pull/1776#discussion_r1958491722
For additional …
=> pkg/client: add Config method to ActionClient

pkg/reconciler/internal/conditions/conditions.go, pkg/reconciler/internal/updater/updater.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
This PR upstreams a feature from the https://github.com/stackrox/helm-operator fork used by ACS (Advanced Cluster Security)
Source commit: https://github.com/stackrox/helm-operator/commit/30a1ac3212ce7b8733cce1e7e31ea18e138997ab
Original PR: https://github.com/stackrox/helm-operator/pull/29
The PR implements support for a "pause reconcile" handler, which determines if the reconcile should be paused for a given custom resource. Also provided is an implementation for such a handler, that allows pausing reconciliation via a custom annotation that must be added to the CR. If this annotation is set to `true` then the operator does not reconcile the CR.
=> ROX-28223: Pause-reconcile handler

pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go
Updated the `setupWatches` method to pass `predicate` if `labelSelector` is set to the reconciler.
If run two reconcilers with the same GVK but different labelSelectors then **both** reconcilers reconcile each other RCs ignoring configured LabelSelectors. This could be considered as not expected behavior if running two or more reconcilers with the same GVK but different labelSelectors is covered scenario. This PR fixes this issue.
Example logs of two reconcilers with the same GVK but different label selector.
There is only one CR with label `app=nginx`. 
**Reconciler1** has `app=nginx` label selector
**Reconciler2** has `app=foo` label selector
**Reconciler1**:
```
2025-03-27T02:58:33+01:00       INFO    controllers.Helm        Watching resource       {"group": "demo.example.com", …
```
=> Pass label selector predicate to the Secret Watch and handler
